force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Company__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chemical</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Mechanical</fullName>
            </value>
            <value>
                <fullName>Tourism</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Company__c.Industry__c</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Employee List</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmployeHelperApexClassTest.cls
@isTest
public class EmployeHelperApexClassTest {
    
    @testSetup
    static void insertCompany(){
        Test.startTest();
        Company__c VarCompanyRec = new Company__c();
        VarCompanyRec.Name = 'Hitachi';
        VarCompanyRec.Industry__c = 'Chemical';
        insert VarCompanyRec;
        Test.stopTest();
    }
    
    @isTest
     static void insertBulkChildRecords(){
        Test.startTest(); 
        List<Employee__c> VarListOfEmployees = new List<Employee__c>();
        Company__c CompanyRec = [SELECT id,Name FROM Company__c WHERE Name = 'Hitachi'];
        System.debug('Company Id ='+CompanyRec.id);
         if(CompanyRec.id != Null){
             for(integer i =0; i<10;i++){
                 Employee__c VarEmpObj = new Employee__c();
                 VarEmpObj.Name = 'Emp'+String.valueOf(i);
                 VarEmpObj.Company__c =CompanyRec.id;
                 VarListOfEmployees.add(VarEmpObj);
             }
             Database.insert(VarListOfEmployees,false);
             System.assertEquals(1, [SELECT id,Name,(SELECT id FROM Employees__r) FROM Company__c WHERE id =:CompanyRec.id].Employees__r.size());
             Test.stopTest();
    
         }
    }
 
}