force-app/main/default/objects/Company__c/Company__c.object-meta.xml
<CustomObject>
    <label>Company</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Companies</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Company__c.Industry__c</field>
            <operation>equals</operation>
            <value>Tourism</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Company__c</referenceTo>
    <relationshipLabel>Employee List</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmployeHelperApexClass.cls
public with sharing class EmployeHelperApexClass{

  public static void checkEmployeeSize(List<Employee__c> VarListOfEmpRec){
      
      Set<ID> SetOfCompanyIds = new Set<ID>();
      for(Employee__c VarEmpRec:VarListOfEmpRec){
          SetOfCompanyIds.add(VarEmpRec.Company__c);
      }
      for(Company__c VarCompanyRec :[SELECT id, Name,(SELECT id FROM Employees__r) FROM Company__c WHERE id IN:SetOfCompanyIds]){
          
          if(VarCompanyRec.id != null){
              if(VarCompanyRec.Employees__r.size()>=1){
                  VarCompanyRec.addError('Only One Record Permitted');
              }else if(VarListOfEmpRec.size() > 1){
                  for(integer i=1;i<VarListOfEmpRec.size();i++){
                      VarListOfEmpRec.get(i).addError('Only One Record Permitted');
                  }
              }
          }
          
      }
      
  }
}