force-app/main/default/objects/AgriFarmer__c/AgriFarmer__c.object-meta.xml
<CustomObject>
    <label>AgriFarmer</label>
    <nameField>
        <label>Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AgriFarmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgriFarmer__c/fields/Final_Expenditure__c.field-meta.xml
<CustomField>
    <fullName>Final_Expenditure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Final Expenditure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AgriFarmer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>&apos;+91&apos;+ Mobile__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AgriFarmer__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <formula>IF(( Earned__c  &gt;  Final_Expenditure__c ),(Earned__c  -  Final_Expenditure__c) , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Farmer_DB__c/Farmer_DB__c.object-meta.xml
<CustomObject>
    <label>Farmer DB</label>
    <nameField>
        <label>Farmer DB Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Farmers DB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Farmer_DB__c/fields/Expenidture__c.field-meta.xml
<CustomField>
    <fullName>Expenidture__c</fullName>
    <label>Expenidture</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Farmer_DB__c/fields/Farmer_Name__c.field-meta.xml
<CustomField>
    <fullName>Farmer_Name__c</fullName>
    <label>Farmer Name</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Farmer_DB__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <label>Profit</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FarmerDBBatch.cls
public class FarmerDBBatch implements Database.Batchable<sObject> {

    public final String query;

    public FarmerDBBatch(String query) {
        this.query = query;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        List<Farmer_DB__c> ls2InsertFarmerDB = new List<Farmer_DB__c>();
        List<AgriFarmer__c> ls2DeleteAgriFarmerDB = new List<AgriFarmer__c>();

        for (sObject rec : scope) {
            AgriFarmer__c agri = (AgriFarmer__c) rec;
            System.debug('Year of CreatedDate: ' + agri.CreatedDate.year());
            
            Farmer_DB__c fa = new Farmer_DB__c();
            fa.Name = agri.Name+' '+'('+ String.valueOf(agri.CreatedDate.year()) + '-' + String.valueOf((agri.CreatedDate.year() + 1)) + ') Agri Report';
            fa.CurrencyIsoCode = 'INR';
            fa.Expenidture__c = agri.Final_Expenditure__c;
            fa.Mobile__c = agri.Phone__c;
            fa.Farmer_Name__c = agri.Name;
            fa.Profit__c = agri.Profit__c;
            ls2InsertFarmerDB.add(fa);
            ls2DeleteAgriFarmerDB.add(agri);
        }
        
        if (!ls2InsertFarmerDB.isEmpty()) {
            insert ls2InsertFarmerDB;
        }
        
        if (!ls2DeleteAgriFarmerDB.isEmpty()) {
            delete ls2DeleteAgriFarmerDB;
        }
    }

    public void finish(Database.BatchableContext bc) {
        // Implement any final operations here
    }
}