force-app/main/default/objects/AgriFarmer__c/AgriFarmer__c.object-meta.xml
<CustomObject>
    <label>AgriFarmer</label>
    <nameField>
        <label>Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AgriFarmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgriFarmer__c/fields/Earned__c.field-meta.xml
<CustomField>
    <fullName>Earned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Earned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AgriFarmer__c/fields/Final_Expenditure__c.field-meta.xml
<CustomField>
    <fullName>Final_Expenditure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Final Expenditure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AgriFarmer__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <formula>IF(( Earned__c  &gt;  Final_Expenditure__c ),(Earned__c  -  Final_Expenditure__c) , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AgriFarmerController.cls
public without sharing class AgriFarmerController {

    @AuraEnabled(cacheable=true)
    public static List<DataSet> getAgriRec() {
        List<DataSet> lsOfData = new List<DataSet>();
        for (AgriFarmer__c a : [SELECT Id, Name, Final_Expenditure__c, Earned__c, Profit__c FROM AgriFarmer__c]) {
            lsOfData.add(new DataSet(a.Name, a.Final_Expenditure__c, a.Earned__c, a.Profit__c));
        }
        return lsOfData;
    }

    public class DataSet {
        @AuraEnabled
        public String name { get; set; }
        @AuraEnabled
        public Decimal finalExp { get; set; }
        @AuraEnabled
        public Decimal earned { get; set; }
        @AuraEnabled
        public Decimal profit { get; set; }

        // Constructor
        public DataSet(String name, Decimal finalExp, Decimal earned, Decimal profit) {
            this.name = name;
            this.finalExp = finalExp;
            this.earned = earned;
            this.profit = profit;
        }
    }
}