force-app/main/default/objects/AgriFarmer__c/AgriFarmer__c.object-meta.xml
<CustomObject>
    <label>AgriFarmer</label>
    <nameField>
        <label>Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AgriFarmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgriFarmer__c/fields/Earned__c.field-meta.xml
<CustomField>
    <fullName>Earned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Earned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AgriFarmer__c/fields/Final_Expenditure__c.field-meta.xml
<CustomField>
    <fullName>Final_Expenditure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Final Expenditure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AgriFarmer__c/fields/Phone__c.field-meta.xml
<CustomField>
    <fullName>Phone__c</fullName>
    <formula>&apos;+91&apos;+ Mobile__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AgriFarmer__c/fields/Profit__c.field-meta.xml
<CustomField>
    <fullName>Profit__c</fullName>
    <formula>IF(( Earned__c  &gt;  Final_Expenditure__c ),(Earned__c  -  Final_Expenditure__c) , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Profit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FarmerDBBatchScheduler.cls
public class FarmerDBBatchScheduler implements Schedulable {
    public void execute(SchedulableContext sc) {
        String query = 'SELECT Id, Name, Earned__c, Phone__c, Profit__c, Final_Expenditure__c, CreatedDate FROM AgriFarmer__c ORDER BY CreatedDate ASC LIMIT 1';
        Database.executeBatch(new FarmerDBBatch(query));
    }

    // Method to schedule the batch job
    public static void scheduleBatch() {
        String cronExp = '0 0 0 25 2 ? *';  // Runs at midnight on February 25th every year
        String jobName = 'Annual FarmerDBBatch Job';
        System.schedule(jobName, cronExp, new FarmerDBBatchScheduler());
    }
}