force-app/main/default/objects/AgriFarmer__c/AgriFarmer__c.object-meta.xml
<CustomObject>
    <label>AgriFarmer</label>
    <nameField>
        <label>Farmer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AgriFarmers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AgriFarmer__c/fields/Final_Expenditure__c.field-meta.xml
<CustomField>
    <fullName>Final_Expenditure__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Final Expenditure</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LabourExpence__c/LabourExpence__c.object-meta.xml
<CustomObject>
    <label>LabourExpence</label>
    <nameField>
        <displayFormat>LEX-{00}</displayFormat>
        <label>LEX</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LabourExpences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/LabourExpence__c/fields/AgriFarmer__c.field-meta.xml
<CustomField>
    <fullName>AgriFarmer__c</fullName>
    <label>AgriFarmer</label>
    <referenceTo>AgriFarmer__c</referenceTo>
    <relationshipLabel>List Of LE</relationshipLabel>
    <relationshipName>LabourExpences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/LabourExpence__c/fields/PastExpence__c.field-meta.xml
<CustomField>
    <fullName>PastExpence__c</fullName>
    <label>PastExpence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/LabourExpence__c/fields/PresentExpence__c.field-meta.xml
<CustomField>
    <fullName>PresentExpence__c</fullName>
    <label>PresentExpence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PesticideExpence__c/PesticideExpence__c.object-meta.xml
<CustomObject>
    <label>PesticideExpence</label>
    <nameField>
        <displayFormat>PEX-{00}</displayFormat>
        <label>PEX</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PesticideExpences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PesticideExpence__c/fields/AgriFarmer__c.field-meta.xml
<CustomField>
    <fullName>AgriFarmer__c</fullName>
    <label>AgriFarmer</label>
    <referenceTo>AgriFarmer__c</referenceTo>
    <relationshipLabel>List Of PE</relationshipLabel>
    <relationshipName>PesticideExpences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SeedsExpence__c/SeedsExpence__c.object-meta.xml
<CustomObject>
    <label>SeedsExpence</label>
    <nameField>
        <displayFormat>CTS-{00}</displayFormat>
        <label>CTSE</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SeedsExpences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SeedsExpence__c/fields/AgriFarmer__c.field-meta.xml
<CustomField>
    <fullName>AgriFarmer__c</fullName>
    <label>AgriFarmer</label>
    <referenceTo>AgriFarmer__c</referenceTo>
    <relationshipLabel>List Of SE</relationshipLabel>
    <relationshipName>SeedsExpences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SeedsExpence__c/fields/PastExpence__c.field-meta.xml
<CustomField>
    <fullName>PastExpence__c</fullName>
    <label>PastExpence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TractorExpence__c/TractorExpence__c.object-meta.xml
<CustomObject>
    <label>TractorExpence</label>
    <nameField>
        <displayFormat>TEX-{00}</displayFormat>
        <label>TEX</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TractorExpences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TractorExpence__c/fields/AgriFarmer__c.field-meta.xml
<CustomField>
    <fullName>AgriFarmer__c</fullName>
    <label>AgriFarmer</label>
    <referenceTo>AgriFarmer__c</referenceTo>
    <relationshipLabel>List Of TE</relationshipLabel>
    <relationshipName>TractorExpences</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TractorExpence__c/fields/PresentExpence__c.field-meta.xml
<CustomField>
    <fullName>PresentExpence__c</fullName>
    <label>PresentExpence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/FinalExpence.cls
public without sharing class FinalExpence {

    public static void updateFinalExp(Map<Id, sObject> newMap) {
        // Map to store AgriFarmer__c Ids with their associated expense records
        Map<Id, List<sObject>> mpOfAgriFarmers = new Map<Id, List<sObject>>();

        // Iterate through the newMap to populate the mpOfAgriFarmers map
        for (Id key : newMap.keySet()) {
            sObject newRecord = newMap.get(key);
            Schema.SObjectType sObjectType = newRecord.getSObjectType();

            if (sObjectType == SeedsExpence__c.sObjectType || sObjectType == TractorExpence__c.sObjectType ||
                sObjectType == LabourExpence__c.sObjectType || sObjectType == PesticideExpence__c.sObjectType) {

                Id farmerId;
                if (sObjectType == SeedsExpence__c.sObjectType) {
                    farmerId = ((SeedsExpence__c)newRecord).AgriFarmer__c;
                } else if (sObjectType == TractorExpence__c.sObjectType) {
                    farmerId = ((TractorExpence__c)newRecord).AgriFarmer__c;
                } else if (sObjectType == LabourExpence__c.sObjectType) {
                    farmerId = ((LabourExpence__c)newRecord).AgriFarmer__c;
                } else if (sObjectType == PesticideExpence__c.sObjectType) {
                    farmerId = ((PesticideExpence__c)newRecord).AgriFarmer__c;
                }

                if (mpOfAgriFarmers.containsKey(farmerId)) {
                    mpOfAgriFarmers.get(farmerId).add(newRecord);
                } else {
                    mpOfAgriFarmers.put(farmerId, new List<sObject>{newRecord});
                }
            }
        }

        // List to store AgriFarmer__c records to be updated
        List<AgriFarmer__c> ls2update = new List<AgriFarmer__c>();

        // Query for AgriFarmer__c records based on the collected Ids in mpOfAgriFarmers
        for (AgriFarmer__c agriRec : [SELECT Id, Final_Expenditure__c FROM AgriFarmer__c WHERE Id IN :mpOfAgriFarmers.keySet()]) {
            List<sObject> lsRec = mpOfAgriFarmers.get(agriRec.Id);

            for (sObject rec : lsRec) {
                Schema.SObjectType sObjectType = rec.getSObjectType();
                Decimal difference = 0;

                if (sObjectType == SeedsExpence__c.sObjectType) {
                    SeedsExpence__c expRec = (SeedsExpence__c)rec;
                    difference = expRec.PresentExpence__c - expRec.PastExpence__c;
                } else if (sObjectType == TractorExpence__c.sObjectType) {
                    TractorExpence__c expRec = (TractorExpence__c)rec;
                    difference = expRec.PresentExpence__c - expRec.PastExpence__c;
                } else if (sObjectType == LabourExpence__c.sObjectType) {
                    LabourExpence__c expRec = (LabourExpence__c)rec;
                    difference = expRec.PresentExpence__c - expRec.PastExpence__c;
                } else if (sObjectType == PesticideExpence__c.sObjectType) {
                    PesticideExpence__c expRec = (PesticideExpence__c)rec;
                    difference = expRec.PresentExpence__c - expRec.PastExpence__c;
                }
                System.debug('Difference :'+difference);
                System.debug('Final_Expenditure__c :'+agriRec.Final_Expenditure__c );

                agriRec.Final_Expenditure__c += difference;
            }

            ls2update.add(agriRec);
        }

        // Update the AgriFarmer__c records if there are any changes
        if (!ls2update.isEmpty()) {
            update ls2update;
        }
    }
}