force-app/main/default/objects/Case_Notification__e/Case_Notification__e.object-meta.xml
<CustomObject>
    <description>Case Notification platform event used to Trigger MuleSoft application</description>
    <label>Case Notification</label>
    <pluralLabel>Case Notifications</pluralLabel>
</CustomObject>

force-app/main/default/objects/Case_Notification__e/fields/CaseId__c.field-meta.xml
<CustomField>
    <fullName>CaseId__c</fullName>
    <label>Case ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case_Notification__e/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <label>Origin</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CasePlatformEventHandler.cls
public class CasePlatformEventHandler {
    public static void invokeMuleFlow(Map<Id, Case> newMap, Map<Id, Case> oldMap){
        set<Id> requiredCaseIds = new set<Id>();
        for(Id i: newMap.keySet()){
            Case newRec = newMap.get(i);
            Case oldRec = oldMap != null? oldMap.get(i) : null;
            if(newRec != null  && newRec.Origin == System.Label.Case_Orgin && newRec.Status != 'Closed' && newRec.Status != 'Working'){
                if(oldRec != null && oldRec.Origin != newRec.Origin){
                    requiredCaseIds.add(i);
                }else{
                    requiredCaseIds.add(i);
                    
                }
                
            }
        }
        if(!requiredCaseIds.isEmpty()){
            List<Case_Notification__e> eventsToPublish = new List<Case_Notification__e>();
            for(Id i: requiredCaseIds){
                eventsToPublish.add(new Case_Notification__e(
                CaseId__c = newMap.get(i).Id,
                Subject__c = newMap.get(i).Subject,
                Origin__c = newMap.get(i).Origin,
                Status__c = newMap.get(i).Status,
                Description__c = newMap.get(i).Description
                ));
            }
            if(!eventsToPublish.isEmpty()){
                EventBus.publish(eventsToPublish);
            }
        }
        
    }

}