force-app/main/default/objects/Parker_Pen__c/Parker_Pen__c.object-meta.xml
<CustomObject>
    <label>Parker Pen</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parker Pens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Parker_Pen__c/fields/Oracle_Ext_ID__c.field-meta.xml
<CustomField>
    <fullName>Oracle_Ext_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Oracle Ext ID</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ParkerPenTriggerTestClass.cls
@isTest
public class ParkerPenTriggerTestClass {
    @isTest
    public static void insertCollectionOfRecords(){
        
        List<Parker_Pen__c> VarListOfParkerRecs = new List<Parker_Pen__c>();
        for(integer i=0;i<200;i++){
            Parker_Pen__c VarParkerRec = new Parker_Pen__c();
            VarParkerRec.Name = 'TestName'+i;
            VarParkerRec.Price__c = 120;
            VarParkerRec.Oracle_Ext_ID__c = 'O'+i;
            VarListOfParkerRecs.add(VarParkerRec);
        }

        Test.startTest();
        insert VarListOfParkerRecs;
        Test.stopTest();
        integer count = [SELECT count() FROM Parker_Pen__c WHERE Price__c =: 100];
        System.assertEquals(200,count , 'Failed to Insert Records');
        
    }
}