force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Chemistry__c.field-meta.xml
<CustomField>
    <fullName>Chemistry__c</fullName>
    <label>Chemistry</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Maths__c.field-meta.xml
<CustomField>
    <fullName>Maths__c</fullName>
    <label>Maths</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Physics__c.field-meta.xml
<CustomField>
    <fullName>Physics__c</fullName>
    <label>Physics</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestClassSampl.cls
@isTEST
public class TestClassSampl{



@isTest
public static void TestMethod1(){


Test.startTest();
  Opportunity op = new Opportunity();
  op.Name = 'TestOpp';
  op.CloseDate = Date.today();
  op.StageName='Qualification';
  insert op;
  Student__c st = new Student__c();
  st.Opportunity__c = op.Id;
  st.Chemistry__c = 10;
  st.Physics__c =10;
  st.Maths__c = 10;
  st.Name = 'Test Name';
  st.Email__c ='Test@gmail.com';
  insert st;  
  
  op.Name = 'TestOpp1';
  update op;

Test.stopTest();
}



}