force-app/main/default/objects/Bank__c/Bank__c.object-meta.xml
<CustomObject>
    <description>This object holds Banks name.</description>
    <label>Bank</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Banks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/Bank_Account__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>Customer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Bank_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <formula>Bank__r.Name +  RIGHT( Id , 7)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bank_Account__c/fields/Bank__c.field-meta.xml
<CustomField>
    <fullName>Bank__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank</label>
    <referenceTo>Bank__c</referenceTo>
    <relationshipLabel>Customers List</relationshipLabel>
    <relationshipName>Bank_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/bankAccountsManager.cls
public with sharing class bankAccountsManager {
    @AuraEnabled(cacheable=true)
    public static List<Bank__c> GetCustomerInformation(String recId){
        try {
            return [SELECT Id, Name, (SELECT Id, Name, Account_Number__c, Mobile__c, RecordType.Name FROM Bank_Accounts__r) FROM Bank__c WHERE Id =: recId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}